<?php

    class LoginController extends DatabaseConnection{

        public function signIn($username, $password) {

            parent::query();// TODO: Change the autogenerated stub

            // Validate the username and password
            // If valid, set session variables and return true
            // Otherwise, return false
        }

        public function signUp($username, $password) {
            // Check if the username already exists in the database
            // If it does not exist, insert a new user record and return true
            // Otherwise, return false
        }

        public function signOut() {
            // Unset session variables and destroy the session
        }
    }



?>